### ISSUE TITLE
Display cursor when in extended mode

### ISSUE THREAD

**Issue by leahneukirchen** [deadpixi/tine#1]
As tine uses the terminal cursor by default, there is no visible cursor in the buffer when in extended mode, which can be confusing when using cursor movement commands.

Perhaps the text cursor could be displayed using inverted colors when in extended mode.

**Comment by deadpixi** [comment]
Good idea. Working on it, but it probably won't happen until I refactor the highlighting code. Thank you.

**Comment by deadpixi** [comment]
Try the latest master please @leahneukirchen

**Comment by leahneukirchen** [comment]
Works great, thanks!
