### ISSUE TITLE
Pressing Enter on first line does not scroll downward

### ISSUE THREAD

**Issue by drj11** [deadpixi/tine#6]
If this is true to AmigaDOS then that's fine, but it's still surprising enough that a note about screen update and scrolling would be welcome.

In a sufficiently large file, the output of `man ls | sed 99q` say, pressing Enter when the cursor is at the beginning of the file apparently has no effect. In fact the file changes correctly, but the fresh empty line has been scrolled out of the way above the cursor.

The first time i noticed the scrolling behaviour of Enter (which i think is: either scroll the lines after the cursor down, or scroll the lines after the cursor up, whichever is the fewer lines) i thought it was unsettling, but then i quite liked it.

But now i've discovered this "entering a blank line at the top of file" i'm unsettled again.

**Comment by deadpixi** [comment]
Yep. This mimics ED’s behavior. The 80’s were a different time.

**Comment by drj11** [comment]
can we have a note about screen updating / scrolling then? and by "have" i mean "have an understanding that this is desirable and will be produced as and when time and effort permits".
