### ISSUE TITLE
Ctrl-U doesn't page up when in first 12 lines

### ISSUE THREAD

**Issue by drj11** [deadpixi/tine#7]
Even if you can't currently see some of those lines because they are "off the top" of the terminal. This feels like it probably is true to the AmgiaDOS ed, but is hilarious.

**Comment by deadpixi** [comment]
Yep. This is Intended Behavior In The Spirit Of ED. 

tine has an extension over ED, the Page Height (PH) command, to set that number.

For the record, tine also follows the AmigaDOS >2.0 meanings for Page Up/Down as opposed to the earlier meaning, which was reversed (“are you scrolling the content down or the viewport down?”). By AmigaDOS 2.0 they succumbed to peer pressure and made “scroll down” mean “show content closer to the end of the file.”

**Comment by drj11** [comment]
Early Jobs-ian scrolling (as in, scrolling in the direction that Steve Jobs intended). noice.
